import { useEffect, useRef, useState } from 'react';
import { Sparkles, Check, LoaderCircle } from 'lucide-react';
import { Modal, RecipeDetail } from './components';
import type { AppData, Recipe } from './types';
import { defaultProfiles, type PlanProposal, type PlanSource, adoptPlan } from './kitchen';
import { keepRecipeImage } from './discovery';
import { api } from './api';
import { weekDates, weekLabel } from './domain';

export function SourceChoice({ value,onChange }: { value:PlanSource;onChange:(v:PlanSource)=>void }) {
  return <label>Rezeptquelle<select value={value} onChange={e=>onChange(e.target.value as PlanSource)}><option value="own">Eigene Rezepte</option><option value="web">Eingelesene Web-Rezepte</option><option value="mixed">Eigene + Web-Rezepte</option><option value="creative">Neue KI-Rezeptideen</option></select></label>;
}
export default function AIPlanner({ data,week,onClose,onApply }: { data:AppData;week:string;onClose:()=>void;onApply:(update:(d:AppData)=>AppData)=>Promise<void> }) {
  const profiles=data.profiles||defaultProfiles();const [ids,setIds]=useState(profiles.map(p=>p.id));const [source,setSource]=useState<PlanSource>('mixed');const [fullDay,setFullDay]=useState(false);const [mealPrep,setMealPrep]=useState(false);const [proposal,setProposal]=useState<PlanProposal|null>(null);const [busy,setBusy]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [preview,setPreview]=useState<Recipe|null>(null);const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  const reset=()=>setProposal(null);
  async function generate(){setBusy(true);setError('');setProposal(null);controller.current=new AbortController();try{const result=await api<PlanProposal>('ai/plan',{source,fullDay,mealPrep,month:new Date(`${week}T12:00:00`).getMonth()+1,profiles:profiles.filter(p=>ids.includes(p.id)),pantry:data.pantry||[],recipes:source==='own'||source==='mixed'?data.recipes.slice(0,100).map(r=>({...r,image:'',photos:[]})):[]},controller.current.signal);setProposal({...result,mealPrep});}catch(e){if(!controller.current?.signal.aborted)setError((e as Error).message);}finally{setBusy(false);}}
  async function apply(){if(!proposal)return;setSaving(true);setError('');try{const recipes:Recipe[]=[];for(const r of proposal.recipes){const own=data.recipes.find(o=>o.id===r.id);recipes.push(own||await keepRecipeImage(r));}await onApply(d=>adoptPlan(d,{...proposal,recipes},week,ids));onClose();}catch(e){setError((e as Error).message);}finally{setSaving(false);}}
  return <Modal title="Woche mit KI planen" wide onClose={()=>{if(!saving){controller.current?.abort();onClose();}}}><div className="modal-body kitchen-form"><p>{weekLabel(week)}</p><p className="field-label">Wer isst mit?</p><div className="filters">{profiles.map(p=><button disabled={busy||saving} key={p.id} className={ids.includes(p.id)?'active':''} aria-pressed={ids.includes(p.id)} onClick={()=>{setIds(ids.includes(p.id)?ids.filter(i=>i!==p.id):[...ids,p.id]);reset();}}>{p.name}</button>)}</div>
    <fieldset disabled={busy||saving}><SourceChoice value={source} onChange={v=>{setSource(v);reset();}}/><label>Umfang<select value={fullDay?'full':'dinner'} onChange={e=>{setFullDay(e.target.value==='full');reset();}}><option value="dinner">7 Abendessen</option><option value="full">7 ganze Tage</option></select></label><label className="checkbox-label"><input type="checkbox" checked={mealPrep} onChange={e=>{setMealPrep(e.target.checked);reset();}}/><span>Meal Prep: Gerichte für mehrere Tage vorkochen</span></label></fieldset>
    <p className="fineprint">Die KI berücksichtigt die gespeicherten Vorlieben und Ausschlüsse aller ausgewählten Profile, Saison und Vorräte. Kalorien sind Schätzungen. {fullDay?'Geplant werden Frühstück, Mittag- und Abendessen.':'Bei „7 Abendessen“ bleibt der übrige Tag offen.'}</p>
    <button className="btn primary full" disabled={busy||saving||!ids.length} onClick={()=>void generate()}>{busy?<LoaderCircle size={20} className="spin"/>:<Sparkles size={20}/>} {busy?'Wochenvorschlag wird erstellt …':'Wochenvorschlag erstellen'}</button>
    {error&&<p className="notice error" role="alert">{error}</p>}
    {proposal&&<section className="plan-proposal"><p className="notice">{proposal.note}</p>{weekDates(week).map((day,index)=>{const meals=proposal.meals.filter(m=>m.dayIndex===index);return <article className="kitchen-panel" key={day}><h3>{new Date(`${day}T12:00:00`).toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'short'})}</h3>{meals.map(m=>{const r=proposal.recipes.find(r=>r.id===m.recipeId)!;return <div className="proposal-meal" key={m.slot}><span className="small">{m.slot}</span><button className="text-btn" onClick={()=>setPreview(r)}>{r.title}</button><p>{m.reason}</p><p className="fineprint">{m.kcalPerServing?`ca. ${Math.round(m.kcalPerServing)} kcal je Portion (KI-Schätzung)`:'Kalorien offen'} · {ids.length} Portionen</p></div>})}{fullDay&&<p className="fineprint">{meals.every(m=>m.kcalPerServing!==null)?`Geplant: ca. ${Math.round(meals.reduce((n,m)=>n+(m.kcalPerServing||0),0))} kcal je Person`:'Tagessumme offen: Nährwerte fehlen'}{profiles.filter(p=>ids.includes(p.id)&&p.calories).map(p=>` · ${p.name}: Ziel ${p.calories} kcal`).join('')}</p>}</article>})}<p className="notice">Beim Übernehmen werden neue Rezepte mit Bild ins Kochbuch gespeichert und die Gerichte zum Wochenplan hinzugefügt. Bereits geplante Mahlzeiten bleiben bestehen. Bei Unverträglichkeiten Zutaten und Produktangaben vor dem Kochen prüfen.</p></section>}
  </div>{proposal&&<div className="modal-footer"><button className="btn primary" disabled={saving||busy} onClick={()=>void apply()}><Check size={20}/>{saving?'Wird gespeichert …':'Plan übernehmen & neue Rezepte speichern'}</button></div>}
  {preview&&<RecipeDetail recipe={preview} discovery onClose={()=>setPreview(null)} onImport={()=>setPreview(null)} importLabel="Zurück zum Wochenvorschlag" alreadySaved importBusy={false} onEdit={()=>{}} onPlan={()=>{}} onDelete={()=>{}} onFavorite={()=>{}}/>}
  </Modal>;
}
