import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Pause, Play, RotateCcw, Timer, X } from 'lucide-react';
import { Modal } from './components';
import type { Recipe } from './types';
import { ingredientText, uid } from './domain';
import { remainingSeconds, stepMinutes, type KitchenTimer } from './cooking';
function restored(recipe:Recipe):{step:number;timers:KitchenTimer[]} {
  try {const raw=JSON.parse(sessionStorage.getItem(`cooking:${recipe.id}`)||'null');if(raw&&Number.isInteger(raw.step)&&Array.isArray(raw.timers))return {step:Math.max(0,Math.min(raw.step,recipe.steps.length-1)),timers:raw.timers.filter((t:KitchenTimer)=>t&&typeof t.id==='string'&&typeof t.label==='string'&&Number.isFinite(t.remaining)&&t.remaining>=0&&(t.endAt===null||Number.isFinite(t.endAt))&&typeof t.done==='boolean').slice(0,10)};}catch{/* Start fresh if session storage is unavailable. */}return {step:0,timers:[]};
}
export default function CookingMode({recipe,servings,onClose}:{recipe:Recipe;servings:number;onClose:()=>void}) {
  const [initial]=useState(()=>restored(recipe));const [step,setStep]=useState(initial.step);const [timers,setTimers]=useState<KitchenTimer[]>(initial.timers);const [minutes,setMinutes]=useState(stepMinutes(recipe.steps[initial.step]||'')||5);const [now,setNow]=useState(Date.now());const [finished,setFinished]=useState(false);const [awake,setAwake]=useState(false);
  const audio=useRef<AudioContext|null>(null);const heading=useRef<HTMLHeadingElement>(null);const alerted=useRef(new Set<string>());
  useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),500);const visible=()=>setNow(Date.now());document.addEventListener('visibilitychange',visible);return()=>{clearInterval(id);document.removeEventListener('visibilitychange',visible);};},[]);
  useEffect(()=>{setMinutes(stepMinutes(recipe.steps[step]||'')||5);heading.current?.focus();},[step,recipe]);
  useEffect(()=>{try{sessionStorage.setItem(`cooking:${recipe.id}`,JSON.stringify({step,timers}));}catch{/* Timer keeps running in memory. */}},[recipe.id,step,timers]);
  useEffect(()=>{
    const expired=timers.filter(t=>t.endAt!==null&&!t.done&&remainingSeconds(t,now)===0);
    if(!expired.length)return;
    for(const t of expired){if(alerted.current.has(t.id))continue;alerted.current.add(t.id);if(audio.current?.state==='running'){const ctx=audio.current;for(let i=0;i<3;i++){const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.connect(gain);gain.connect(ctx.destination);oscillator.frequency.value=880;gain.gain.value=.15;oscillator.start(ctx.currentTime+i*.35);oscillator.stop(ctx.currentTime+i*.35+.2);}}navigator.vibrate?.([200,100,200]);}
    setTimers(ts=>ts.map(t=>expired.some(e=>e.id===t.id)?{...t,done:true,endAt:null,remaining:0}:t));
  },[now,timers]);
  useEffect(()=>{let lock:WakeLockSentinel|undefined;let active=true;const acquire=async()=>{try{if(document.visibilityState==='visible'&&'wakeLock'in navigator){const next=await navigator.wakeLock.request('screen');if(!active){void next.release();return;}lock=next;setAwake(true);next.addEventListener('release',()=>{if(active)setAwake(false);});}}catch{if(active)setAwake(false);}};void acquire();document.addEventListener('visibilitychange',acquire);return()=>{active=false;document.removeEventListener('visibilitychange',acquire);void lock?.release();void audio.current?.close();};},[]);
  function startTimer(){if(!Number.isFinite(minutes)||minutes<=0||minutes>1440||timers.length>=10)return;try{audio.current ||= new AudioContext();void audio.current.resume();}catch{/* Visual alarm remains available. */}setTimers(ts=>[...ts,{id:uid(),label:`Schritt ${step+1} · ${minutes} Min.`,endAt:Date.now()+minutes*60000,remaining:minutes*60,done:false}]);}
  return <Modal title="Kochmodus" wide onClose={onClose}><div className="modal-body cook-mode"><p className="cook-recipe">{recipe.title} · {servings} Portionen</p><p className="fineprint">{awake?'Bildschirm bleibt beim Kochen an.':'Lass die App beim Kochen geöffnet.'} Töne funktionieren bei geöffneter App. Im Hintergrund oder bei gesperrtem Handy kann der Alarm ausbleiben; die Restzeit wird beim Zurückkehren korrigiert.</p>
    <details className="cook-ingredients"><summary>Zutaten für {servings} Portionen</summary><ul className="ingredient-list">{recipe.ingredients.map((i,n)=><li key={n}>{ingredientText(i,servings/recipe.servings)}</li>)}</ul></details>
    {finished?<div className="empty-state"><Check size={44}/><h2>Guten Appetit!</h2><button className="btn" onClick={()=>{setFinished(false);setStep(0);}}>Schritte noch einmal ansehen</button></div>:<><div className="cook-progress"><span>Schritt {step+1} von {recipe.steps.length}</span><progress value={step+1} max={recipe.steps.length}/></div><h2 ref={heading} tabIndex={-1} className="cook-step">{recipe.steps[step]}</h2><div className="button-row cook-navigation"><button className="btn" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={20}/>Zurück</button><button className="btn primary" onClick={()=>step===recipe.steps.length-1?setFinished(true):setStep(step+1)}>{step===recipe.steps.length-1?'Fertig':'Nächster Schritt'}<ArrowRight size={20}/></button></div></>}
    <section className="timer-panel"><h3><Timer size={22}/>Küchentimer</h3><div className="timer-add"><label>Minuten<input type="number" min={.1} max={1440} step={.1} inputMode="decimal" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><button className="btn primary" disabled={!minutes||minutes<.1||minutes>1440||timers.length>=10} onClick={startTimer}><Play size={18}/>Timer starten</button></div>
      {timers.map(t=>{const remaining=remainingSeconds(t,now);return <div className={`timer-row ${t.done?'timer-done':''}`} key={t.id}><div><span>{t.label}</span><strong role={t.done?'status':undefined}>{t.done?'Zeit abgelaufen':`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`}</strong></div>{!t.done&&<button className="icon-btn" aria-label={t.endAt?'Timer pausieren':'Timer fortsetzen'} onClick={()=>setTimers(ts=>ts.map(x=>x.id===t.id?{...x,endAt:x.endAt?null:Date.now()+x.remaining*1000,remaining:remainingSeconds(x)}:x))}>{t.endAt?<Pause size={20}/>:<Play size={20}/>}</button>}<button className="icon-btn" aria-label="Timer entfernen" onClick={()=>setTimers(ts=>ts.filter(x=>x.id!==t.id))}><X size={20}/></button></div>})}
    </section><button className="text-btn" onClick={()=>{setStep(0);setFinished(false);}}><RotateCcw size={18}/>Zum ersten Schritt</button>
  </div></Modal>;
}
