import { useState } from 'react';
import { ChefHat, Plus } from 'lucide-react';
import type { AppData, Recipe } from './types';
import { Modal, Portions } from './components';
import { uid, weekDates } from './domain';
export function MealPrepEditor({data,week,onSave,onClose}:{data:AppData;week:string;onSave:(update:(d:AppData)=>AppData)=>Promise<void>;onClose:()=>void}) {
  const [recipeId,setRecipeId]=useState(data.recipes[0]?.id||'');const [days,setDays]=useState([week]);const [cookDay,setCookDay]=useState(week);const [servings,setServings]=useState(3);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  return <Modal title="Meal Prep planen" onClose={()=>{if(!busy)onClose();}}><form className="modal-body kitchen-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const batch=uid();await onSave(d=>{const plan={...d.plan};for(const day of days)plan[day]=[...(plan[day]||[]),{id:uid(),recipeId,servings,slot:'Abendessen',batchId:batch,cookDay}];return {...d,plan};});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
    <label>Welches Rezept?<select required value={recipeId} onChange={e=>setRecipeId(e.target.value)}>{data.recipes.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><label>Wann wird vorgekocht?<input type="date" required max={days.slice().sort()[0]} value={cookDay} onChange={e=>setCookDay(e.target.value)}/></label><p className="field-label">An diesen Tagen essen</p><div className="filters">{weekDates(week).map(day=><button type="button" key={day} aria-pressed={days.includes(day)} className={days.includes(day)?'active':''} onClick={()=>setDays(days.includes(day)?days.filter(x=>x!==day):[...days,day])}>{new Date(`${day}T12:00:00`).toLocaleDateString('de-DE',{weekday:'short',day:'numeric'})}</button>)}</div><p className="field-label">Portionen je Mahlzeit</p><Portions value={servings} onChange={setServings}/><p className="notice">Einmal {days.length*servings} Portionen kochen, auf {days.length} Mahlzeiten verteilen. Die Einkaufsliste berechnet diese Gesamtmenge.</p><p className="fineprint">Vorgekochtes zügig abkühlen und gekühlt aufbewahren. Für spätere Tage passende Portionen einfrieren. Haltbarkeit hängt vom Gericht ab; insbesondere bei Reis, Fisch oder Fleisch sorgfältig planen. <a href="https://www.bfr.bund.de/fragen-und-antworten/thema/vorkochen-fuer-mehrere-tage/" target="_blank" rel="noopener noreferrer">Hinweise des BfR</a></p><button className="btn primary full" disabled={busy||!recipeId||!days.length||!cookDay}><Plus size={20}/>Meal Prep zum Wochenplan hinzufügen</button>{error&&<p className="notice error" role="alert">{error}</p>}
  </form></Modal>;
}
export function MealPrepBatches({data,week,onCook}:{data:AppData;week:string;onCook:(recipe:Recipe,servings:number)=>void}) {
  const visibleDays=new Set(weekDates(week));
  const visibleIds=new Set(Object.entries(data.plan).filter(([day])=>visibleDays.has(day)).flatMap(([,entries])=>entries.map(e=>e.batchId).filter(Boolean)));
  const batches=new Map<string,{recipe:Recipe;servings:number;cookDay:string;days:string[]}>();
  for(const [day,entries]of Object.entries(data.plan))for(const e of entries){if(!e.batchId||!visibleIds.has(e.batchId))continue;const recipe=data.recipes.find(r=>r.id===e.recipeId);if(!recipe)continue;const key=`${e.batchId}:${e.recipeId}`;const existing=batches.get(key);if(existing){existing.servings+=e.servings;existing.days.push(day);}else batches.set(key,{recipe,servings:e.servings,cookDay:e.cookDay||day,days:[day]});}
  return batches.size>0?<section className="mealprep-batches"><h2>Deine Vorkochrunden</h2>{[...batches].map(([id,b])=><article className="kitchen-panel" key={id}><h3>{b.recipe.title}</h3><p>{b.servings} Portionen vorkochen am {new Date(`${b.cookDay}T12:00:00`).toLocaleDateString('de-DE',{weekday:'short',day:'numeric',month:'short'})}</p><p className="fineprint">Essen am {b.days.sort().map(d=>new Date(`${d}T12:00:00`).toLocaleDateString('de-DE',{weekday:'short',day:'numeric'})).join(', ')}. Die Gesamtmenge steht in der Einkaufsliste der jeweiligen Essenswoche.</p><button className="btn primary" disabled={!b.recipe.steps.length} onClick={()=>onCook(b.recipe,b.servings)}><ChefHat size={20}/>Vorkochen starten</button></article>)}</section>:null;
}
