import { useEffect, useMemo, useRef, useState } from 'react';
import { Camera, Plus, Sparkles, X, LoaderCircle, Refrigerator, Search } from 'lucide-react';
import type { AppData, PantryItem, Recipe } from './types';
import { defaultProfiles, pantryMatch, profileConflicts, type PlanSource } from './kitchen';
import { uid, localDate } from './domain';
import { compressPhoto } from './ocr';
import { api } from './api';
import { discoverRecipes, keepRecipeImage } from './discovery';
import { RecipeDetail, RecipeImage } from './components';
import { SourceChoice } from './AIPlanner';

type Detection = { name:string;quantity:string;uncertain:boolean;selected:boolean };
export default function Pantry({ data,onChange,onAdd,onOpen }: { data:AppData;onChange:(update:(d:AppData)=>AppData)=>Promise<void>;onAdd:(r:Recipe)=>Promise<void>;onOpen:(id:string)=>void }) {
  const pantry=data.pantry||[];const profiles=data.profiles||defaultProfiles();
  const [name,setName]=useState('');const [quantity,setQuantity]=useState('');const [location,setLocation]=useState<PantryItem['location']>('fridge');const [expires,setExpires]=useState('');
  const [photos,setPhotos]=useState<string[]>([]);const [detected,setDetected]=useState<Detection[]>([]);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [note,setNote]=useState('');const [source,setSource]=useState<PlanSource>('mixed');const [ids,setIds]=useState(profiles.map(p=>p.id));const [suggestions,setSuggestions]=useState<Recipe[]|null>(null);const [selected,setSelected]=useState<Recipe|null>(null);const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  const activeProfiles=profiles.filter(p=>ids.includes(p.id));
  const matches=useMemo(()=>{
    const pool=source==='own'?data.recipes:source==='web'?discoverRecipes.filter(r=>!r.sample):source==='creative'?[]:[...data.recipes,...discoverRecipes.filter(r=>!r.sample)];
    return [...new Map(pool.map(r=>[r.id,r])).values()].filter(r=>!profileConflicts(r,activeProfiles).length&&pantryMatch(r,pantry).have.length).sort((a,b)=>pantryMatch(b,pantry).score-pantryMatch(a,pantry).score).slice(0,8);
  },[data.recipes,pantry,source,ids,data.profiles]);
  async function run(label:string,fn:()=>Promise<void>){if(busy)return;setBusy(label);setError('');try{await fn();}catch(e){if(!controller.current?.signal.aborted)setError((e as Error).message);}finally{setBusy('');}}
  async function addPhotos(files:FileList|null){if(!files?.length)return;await run('photos',async()=>{if(photos.length+files.length>6)throw new Error('Bitte höchstens sechs Fotos auswählen.');const next=[...photos];for(const file of files)next.push(await compressPhoto(file));setPhotos(next);setDetected([]);});}
  const saved=(r:Recipe)=>data.recipes.find(o=>o.id===r.id||r.sourceUrl&&r.sourceUrl===o.sourceUrl);
  async function add(r:Recipe){if(saved(r)){setSelected(null);onOpen(saved(r)!.id);return;}await run('save',async()=>{await onAdd(await keepRecipeImage(r));setSelected(null);});}
  return <><section className="kitchen-panel"><h2><Refrigerator size={24}/>Was ist zu Hause?</h2>
    <label>Aufbewahrung<select value={location} onChange={e=>setLocation(e.target.value as PantryItem['location'])}><option value="fridge">Kühlschrank</option><option value="cupboard">Vorratsschrank</option></select></label>
    <div className="button-row"><label className="btn file-btn"><Camera size={20}/>Foto aufnehmen<input type="file" accept="image/*" capture="environment" disabled={!!busy} onChange={e=>{void addPhotos(e.target.files);e.target.value='';}}/></label><label className="btn file-btn">Mehrere Fotos auswählen<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple disabled={!!busy} onChange={e=>{void addPhotos(e.target.files);e.target.value='';}}/></label></div>
    {!!photos.length&&<><div className="photo-strip">{photos.map((p,i)=><div key={i}><img src={p} alt={`Vorratsfoto ${i+1}`}/><button disabled={!!busy} aria-label={`Vorratsfoto ${i+1} entfernen`} onClick={()=>{setPhotos(photos.filter((_,n)=>n!==i));setDetected([]);}}><X size={20}/></button></div>)}</div><p className="fineprint">Die ausgewählten Fotos werden bei der Erkennung an OpenRouter übermittelt. Erkanntes bitte vor dem Übernehmen prüfen; Frische und Haltbarkeit lassen sich aus Fotos nicht sicher bestimmen.</p><button className="btn primary" disabled={!!busy} onClick={()=>void run('scan',async()=>{controller.current=new AbortController();const result=await api<{items:Omit<Detection,'selected'>[];note:string}>('ai/pantry',{images:photos},controller.current.signal);setDetected(result.items.map(i=>({...i,selected:!i.uncertain})));setNote(result.note);})}>{busy==='scan'?<LoaderCircle className="spin" size={20}/>:<Sparkles size={20}/>}Lebensmittel erkennen</button></>}
    {!!detected.length&&<section><h3>Erkennung prüfen</h3><p className="fineprint">{note}</p>{detected.map((item,i)=><div className="detection-row" key={i}><input aria-label={`${item.name} übernehmen`} type="checkbox" checked={item.selected} onChange={e=>setDetected(d=>d.map((x,n)=>i===n?{...x,selected:e.target.checked}:x))}/><div><label>Lebensmittel{item.uncertain&&<span className="optional"> · unsicher</span>}<input maxLength={200} value={item.name} onChange={e=>setDetected(d=>d.map((x,n)=>i===n?{...x,name:e.target.value}:x))}/></label><label>Menge<input maxLength={100} value={item.quantity} onChange={e=>setDetected(d=>d.map((x,n)=>i===n?{...x,quantity:e.target.value}:x))}/></label></div></div>)}<button className="btn primary" disabled={!!busy||!detected.some(i=>i.selected&&i.name.trim())} onClick={()=>void run('save',async()=>{await onChange(d=>({...d,pantry:[...(d.pantry||[]),...detected.filter(i=>i.selected&&i.name.trim()).map(i=>({id:uid(),name:i.name.trim(),quantity:i.quantity,location,expires:''}))]}));setDetected([]);setPhotos([]);setSuggestions(null);})}>Geprüfte Lebensmittel übernehmen</button></section>}
    <details className="manual-pantry" open={!pantry.length&&!photos.length}><summary>Lebensmittel manuell ergänzen</summary><form onSubmit={e=>{e.preventDefault();void run('save',async()=>{if(!name.trim())return;await onChange(d=>({...d,pantry:[...(d.pantry||[]),{id:uid(),name:name.trim(),quantity,location,expires}]}));setName('');setQuantity('');setExpires('');setSuggestions(null);});}}><label>Lebensmittel<input required maxLength={200} value={name} onChange={e=>setName(e.target.value)} placeholder="Zum Beispiel Tomaten"/></label><div className="form-two"><label>Menge<input maxLength={100} value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="500 g oder 3 Stück"/></label><label>Zuerst verbrauchen bis <span className="optional">optional</span><input type="date" value={expires} onChange={e=>setExpires(e.target.value)}/></label></div><button className="btn primary" disabled={!!busy}><Plus size={20}/>Zum Vorrat</button></form></details>
  </section>
  {['fridge','cupboard'].map(place=><section className="kitchen-panel" key={place}><h2>{place==='fridge'?'Kühlschrank':'Vorratsschrank'}</h2>{pantry.filter(p=>p.location===place).sort((a,b)=>(a.expires||'9999').localeCompare(b.expires||'9999')).map(p=><div className="pantry-row" key={p.id}><span><strong>{p.name}</strong><small>{p.quantity||'Menge offen'}{p.expires?` · ${p.expires<localDate(new Date())?'Datum prüfen: ':'Verbrauchen bis '}${new Date(`${p.expires}T12:00:00`).toLocaleDateString('de-DE')}`:''}</small></span><button className="icon-btn" aria-label={`${p.name} aus dem Vorrat entfernen`} onClick={()=>void run('save',async()=>{await onChange(d=>({...d,pantry:(d.pantry||[]).filter(x=>x.id!==p.id)}));setSuggestions(null);})}><X size={22}/></button></div>)}{!pantry.some(p=>p.location===place)&&<p className="muted">Hier ist noch nichts eingetragen.</p>}</section>)}
  <section className="kitchen-panel"><h2><Search size={24}/>Mit dem Vorrat kochen</h2><div className="filters">{profiles.map(p=><button key={p.id} aria-pressed={ids.includes(p.id)} className={ids.includes(p.id)?'active':''} onClick={()=>{setIds(ids.includes(p.id)?ids.filter(x=>x!==p.id):[...ids,p.id]);setSuggestions(null);}}>{p.name}</button>)}</div><SourceChoice value={source} onChange={v=>{setSource(v);setSuggestions(null);}}/><button className="btn primary" disabled={!!busy||!pantry.length||!ids.length} onClick={()=>void run('recommend',async()=>{controller.current=new AbortController();const result=await api<{recipes:Recipe[];note:string}>('ai/recommend',{source,profiles:activeProfiles,pantry,recipes:source==='own'||source==='mixed'?data.recipes.slice(0,100).map(r=>({...r,image:'',photos:[]})):[]},controller.current.signal);setSuggestions(result.recipes.map(r=>data.recipes.find(o=>o.id===r.id)||r));setNote(result.note);})}>{busy==='recommend'?<LoaderCircle className="spin" size={20}/>:<Sparkles size={20}/>}KI-Rezeptvorschläge</button><p className="fineprint">{suggestions?'KI-Auswahl: '+note:'Die folgenden Treffer werden nach vorhandenen Zutaten sortiert. Mit der KI erhältst du eine zusätzliche Auswahl anhand eurer Profile.'}</p></section>
  {error&&<p className="notice error" role="alert">{error}</p>}<div className="recipe-grid">{(suggestions||matches).map(r=>{const match=pantryMatch(r,pantry);return <article className="recipe-card" key={r.id}><div className="card-image"><button className="image-button" onClick={()=>setSelected(r)} aria-label={`${r.title} ansehen`}><RecipeImage recipe={r}/></button></div><div className="card-body"><h3><button onClick={()=>setSelected(r)}>{r.title}</button></h3><p className="fineprint">{match.have.length} von {r.ingredients.length} Zutaten im Vorrat erkannt. Mengen bitte prüfen.</p><p className="fineprint">Noch nötig: {match.missing.map(i=>i.name).join(', ')||'Keine weitere Zutat erkannt'}</p><button className="btn primary full" disabled={!!busy} onClick={()=>void add(r)}>{saved(r)?'Im Kochbuch öffnen':'Ins Kochbuch'}</button></div></article>})}</div>
  {(suggestions||matches).length===0&&<p className="notice">{!pantry.length?'Erfasse zuerst deine Vorräte.':'Noch keine passenden Treffer. Mit „Neue KI-Rezeptideen“ kann die KI etwas zu deinen Vorräten entwerfen.'}</p>}
  {selected&&<RecipeDetail recipe={selected} discovery onClose={()=>setSelected(null)} onImport={()=>void add(selected)} importBusy={!!busy} alreadySaved={!!saved(selected)} importError={error} onEdit={()=>{}} onPlan={()=>{}} onDelete={()=>{}} onFavorite={()=>{}}/>}</>;
}
