import { useMemo, useState } from 'react';
import { CalendarDays, Plus, ExternalLink } from 'lucide-react';
import { inSeason, months, produce, seasonalIngredients, seasonSource } from './seasons';
import { discoverRecipes, keepRecipeImage } from './discovery';
import { normalize } from './kitchen';
import { RecipeDetail, RecipeImage } from './components';
import type { Recipe } from './types';
export default function SeasonCalendar({ ownRecipes,onAdd,onOpen }: { ownRecipes:Recipe[];onAdd:(r:Recipe)=>Promise<void>;onOpen:(id:string)=>void }) {
  const [month,setMonth]=useState(new Date().getMonth()+1);const [ingredient,setIngredient]=useState('Alle');const [selected,setSelected]=useState<Recipe|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const available=inSeason(month);
  const recipes=useMemo(()=>discoverRecipes.filter(r=>!r.sample&&seasonalIngredients(r,month).length&&(ingredient==='Alle'||r.ingredients.some(i=>produce.find(p=>p.name===ingredient)?.terms.some(t=>normalize(i.name).includes(normalize(t)))))),[month,ingredient]);
  const saved=(r:Recipe)=>ownRecipes.find(o=>o.id===r.id||r.sourceUrl&&r.sourceUrl===o.sourceUrl);
  async function add(r:Recipe){if(saved(r)){setSelected(null);onOpen(saved(r)!.id);return;}setBusy(true);setError('');try{await onAdd(await keepRecipeImage(r));setSelected(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><section className="kitchen-panel"><h2><CalendarDays size={24}/>Saisonkalender</h2><label>Monat<select value={month} onChange={e=>{setMonth(Number(e.target.value));setIngredient('Alle');}}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><p>Deutschland · ungefähre Erntezeiten. Wetter und Region können den Saisonbeginn verschieben.</p><div className="season-grid">{available.map(p=><button key={p.name} className={`season-tile ${ingredient===p.name?'active':''}`} aria-pressed={ingredient===p.name} onClick={()=>setIngredient(ingredient===p.name?'Alle':p.name)}><strong>{p.name}</strong><span>{p.fresh.includes(month)?'Erntezeit':'Aus Lagerung'}</span></button>)}</div><a className="text-btn" href={seasonSource} target="_blank" rel="noopener noreferrer">Kalender der Verbraucherzentrale <ExternalLink size={16}/></a></section>
    <div className="section-heading"><h2>{ingredient==='Alle'?`Web-Rezepte für ${months[month-1]}`:`Rezepte mit ${ingredient}`}</h2>{ingredient!=='Alle'&&<button className="btn" onClick={()=>setIngredient('Alle')}>Alle Saisonrezepte</button>}</div><p className="fineprint">Passende Rezepte aus dem eingelesenen Wikibooks-Katalog. Die markierten saisonalen Zutaten sind enthalten; andere Zutaten können ganzjährig oder importiert sein.</p>
    {error&&<p className="notice error" role="alert">{error}</p>}<div className="recipe-grid">{recipes.map(r=><article className="recipe-card discovery-card" key={r.id}><div className="card-image"><button className="image-button" onClick={()=>setSelected(r)} aria-label={`${r.title} ansehen`}><RecipeImage recipe={r}/></button><span className="sample-label">Symbolbild</span></div><div className="card-body"><div className="card-tags">{seasonalIngredients(r,month).join(' · ')}</div><h3><button onClick={()=>setSelected(r)}>{r.title}</button></h3><button className="btn primary full" disabled={busy} onClick={()=>void add(r)}><Plus size={18}/>{saved(r)?'Im Kochbuch öffnen':'Ins Kochbuch'}</button></div></article>)}</div>{!recipes.length&&<p className="notice">Zu dieser Auswahl gibt es noch kein Rezept im Web-Katalog. Wähle eine andere Zutat oder importiere ein passendes Rezept per Link.</p>}
    {selected&&<RecipeDetail recipe={selected} discovery onClose={()=>setSelected(null)} onImport={()=>void add(selected)} importBusy={busy} alreadySaved={!!saved(selected)} importError={error} onEdit={()=>{}} onPlan={()=>{}} onDelete={()=>{}} onFavorite={()=>{}}/>}</>;
}
