import type { AppData, Recipe } from './types';
import { parseIngredient } from './domain';

function sample(id: string, title: string, description: string, minutes: number, image: string, tags: string[], ingredients: string[], steps: string[]): Recipe {
  return { id, title, description, minutes, image: `images/${image}.webp`, tags, ingredients: ingredients.map(parseIngredient), steps, servings: 2, photos: [], source: 'Beispielrezept · Tisch & Tag', sourceUrl: '', favorite: false, sample: true, createdAt: '2026-09-13T12:00:00.000Z' };
}
export const exampleRecipes: Recipe[] = [
  sample('sample-bowl', 'Bunte Couscous-Bowl', 'Knackiges Gemüse, lockerer Couscous und ein frisches Zitronendressing.', 20, 'bowl', ['Vegetarisch', 'Schnell'], ['150 g Couscous', '200 ml Gemüsebrühe', '1 Gurke', '250 g Tomaten', '100 g Feta', '1 Zitrone', '2 EL Olivenöl', 'Salz und Pfeffer'], ['Couscous mit der kochenden Gemüsebrühe übergiessen, abdecken und 5 Minuten quellen lassen.', 'Gurke und Tomaten waschen und würfeln. Den Feta zerbröseln.', 'Zitrone auspressen. Den Saft mit Olivenöl, Salz und Pfeffer verrühren.', 'Couscous mit einer Gabel auflockern, mit Gemüse und Dressing mischen und mit Feta servieren.']),
  sample('sample-pasta', 'Pasta mit Ofentomaten', 'Wenig Aufwand, viel Geschmack. Die Tomaten machen die Sauce fast von selbst.', 30, 'pasta', ['Vegetarisch'], ['200 g Pasta', '400 g Tomaten', '2 Zehen Knoblauch', '2 EL Olivenöl', '30 g Parmesan', 'Basilikum', 'Salz und Pfeffer'], ['Ofen auf 200 °C Ober-/Unterhitze vorheizen. Tomaten halbieren und den Knoblauch fein schneiden.', 'Tomaten und Knoblauch mit Olivenöl, Salz und Pfeffer in einer Form mischen und etwa 20 Minuten rösten.', 'Pasta nach Packungsangabe in Salzwasser kochen. Vor dem Abgiessen eine Tasse Kochwasser aufheben.', 'Tomaten leicht zerdrücken. Mit Pasta und bei Bedarf etwas Kochwasser mischen. Mit Parmesan und Basilikum servieren.']),
  sample('sample-curry', 'Kichererbsen-Spinat-Curry', 'Ein unkompliziertes Curry für den Feierabend. Schmeckt auch am nächsten Tag.', 25, 'curry', ['Vegan', 'Gut vorzubereiten'], ['240 g Kichererbsen, abgetropft', '200 g Spinat', '200 ml Kokosmilch', '1 Zwiebel', '1 EL Olivenöl', '2 TL Currypulver', '120 g Reis', 'Salz und Pfeffer'], ['Reis nach Packungsangabe kochen.', 'Zwiebel würfeln und im Öl glasig dünsten. Currypulver kurz mitrösten.', 'Kichererbsen und Kokosmilch dazugeben. Etwa 10 Minuten sanft köcheln lassen; bei Bedarf etwas Wasser ergänzen.', 'Spinat unterheben und zusammenfallen lassen. Mit Salz und Pfeffer abschmecken und mit Reis servieren.']),
  sample('sample-salad', 'Knackiger Gartensalat', 'Ein frischer Salat mit Kichererbsen und einem schnellen Senfdressing.', 15, 'salad', ['Vegan', 'Schnell'], ['150 g Blattsalat', '1 Gurke', '200 g Tomaten', '240 g Kichererbsen, abgetropft', '2 EL Olivenöl', '1 EL Apfelessig', '1 TL Senf', 'Salz und Pfeffer'], ['Salat waschen und trockenschleudern. Gurke und Tomaten klein schneiden.', 'Kichererbsen abspülen und gut abtropfen lassen.', 'Olivenöl, Essig und Senf verrühren. Mit Salz und Pfeffer würzen.', 'Alle Zutaten kurz vor dem Essen mit dem Dressing mischen.']),
  sample('sample-oats', 'Beeren-Porridge', 'Ein warmer Start in den Tag mit Haferflocken, Beeren und Mandeln.', 10, 'oats', ['Vegetarisch', 'Schnell'], ['100 g Haferflocken', '300 ml Milch', '100 ml Wasser', '150 g Beeren', '20 g Mandeln', '1 Prise Salz'], ['Haferflocken mit Milch, Wasser und einer Prise Salz aufkochen.', 'Bei niedriger Hitze unter Rühren etwa 5 Minuten quellen lassen. Falls nötig etwas Wasser dazugeben.', 'Beeren waschen und Mandeln grob hacken. Porridge auf Schalen verteilen und damit garnieren.']),
  sample('sample-veg', 'Ofengemüse mit Feta', 'Ein Blech, buntes Gemüse und Zeit für dich, während der Ofen arbeitet.', 40, 'vegetables', ['Vegetarisch', 'Gut vorzubereiten'], ['400 g Kartoffeln', '1 Zucchini', '2 Karotten', '1 Paprika', '150 g Feta', '2 EL Olivenöl', '1 TL Paprikapulver', 'Salz und Pfeffer'], ['Ofen auf 200 °C Ober-/Unterhitze vorheizen. Kartoffeln und Gemüse waschen, bei Bedarf schälen und in mundgerechte Stücke schneiden.', 'Mit Öl, Paprikapulver, Salz und Pfeffer mischen und auf einem Backblech verteilen.', 'Etwa 25 Minuten backen, dabei einmal wenden. Feta darüberbröseln und weitere 10 Minuten backen, bis die Kartoffeln gar sind.']),
];
export function initialData(): AppData { return { version: 1, recipes: [], plan: {}, checked: {}, extras: [] }; }
