import { useEffect, useState } from 'react';
import { Download, Upload, ShieldCheck, Smartphone, Cloud, LogOut, LoaderCircle, Mail } from 'lucide-react';
import type { AppData } from './types';
import { validateBackup } from './domain';
import { downloadBackup } from './storage';
import { cloud, cloudUser, sendLogin, pushCloud, pullCloud, acceptCloudRevision } from './cloud';
import { Modal } from './components';

export default function Settings({ data, onReplace, onClose }: { data: AppData; onReplace: (d: AppData) => Promise<void>; onClose: () => void }) {
  const [email, setEmail] = useState(''); const [userEmail, setUserEmail] = useState('');
  const signOut = async () => { if (!cloud) return; const { error } = await cloud.auth.signOut(); if (error) throw error; setUserEmail(''); setMessage('Abgemeldet. Das Kochbuch bleibt auf diesem Gerät gespeichert.'); };
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [pending, setPending] = useState<{ data: AppData; revision?: number; userId?: string } | null>(null);
  useEffect(() => { void cloudUser().then(u => setUserEmail(u?.email || '')); }, []);
  async function run(action: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await action(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Modal title="Dein Kochbuch bleibt deins" onClose={onClose}><div className="modal-body settings">
    <div className="settings-intro"><span className="round-icon"><ShieldCheck size={28} /></span><div><h3>Auf diesem Gerät gespeichert</h3><p>Rezepte, Fotos und Wochenpläne bleiben in diesem Browser erhalten. Sichere sie regelmässig, besonders bevor du Browserdaten löschst.</p></div></div>
    <section><h3>Sicherung</h3><p className="muted">Dein komplettes Kochbuch als Datei – auch zum Übertragen auf ein anderes Gerät.</p><div className="button-row wrap"><button className="btn primary" onClick={() => downloadBackup(data)}><Download size={17} />Sicherung herunterladen</button><label className={`btn file-btn ${busy ? 'disabled' : ''}`}><Upload size={17} />Sicherung laden<input type="file" accept="application/json,.json" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (file) void run(async () => { if (file.size > 100_000_000) throw new Error('Diese Datei ist zu gross (maximal 100 MB).'); setPending({ data: validateBackup(JSON.parse(await file.text())) }); }); e.target.value = ''; }} /></label></div></section>
    <section><h3><Cloud size={20} />Auf mehreren Geräten</h3>{!cloud ? <p className="muted">Die Online-Speicherung wird als Nächstes eingerichtet. Bis dahin kannst du dein Kochbuch mit einer Sicherungsdatei mitnehmen.</p> : userEmail ? <><p>Angemeldet als <strong>{userEmail}</strong></p><p className="muted">Lade vor dem Wechsel zum anderen Gerät deine Änderungen hoch. Dort kannst du den aktuellen Stand herunterladen. Die Übertragung erfolgt über diese beiden Schaltflächen.</p><div className="button-row wrap"><button className="btn primary" disabled={busy} onClick={() => void run(async () => { await pushCloud(data); setMessage('Dein Kochbuch ist in der Cloud gesichert.'); })}><Upload size={17} />In Cloud sichern</button><button className="btn" disabled={busy} onClick={() => void run(async () => { setPending(await pullCloud()); })}><Download size={17} />Cloud-Stand laden</button><button className="text-btn" disabled={busy} onClick={() => void run(signOut)}><LogOut size={15} />Abmelden</button></div></> : <form onSubmit={e => { e.preventDefault(); void run(async () => { await sendLogin(email); setMessage('Wenn die Adresse für diese App freigeschaltet ist, kommt gleich ein Anmeldelink per E-Mail.'); }); }}><p className="muted">Melde dich mit deiner freigeschalteten E-Mail-Adresse an.</p><label>E-Mail-Adresse<input type="email" autoComplete="email" required value={email} onChange={e => setEmail(e.target.value)} /></label><button className="btn primary" disabled={busy}><Mail size={17} />Anmeldelink senden</button></form>}</section>
    {pending && <section className="notice"><h3>Kochbuch ersetzen?</h3><p>Die Sicherung enthält {pending.data.recipes.length} Rezepte. Der aktuelle Stand auf diesem Gerät wird ersetzt. Lade vorher bei Bedarf eine Sicherung herunter.</p><div className="button-row wrap"><button className="btn" onClick={() => downloadBackup(data)}>Aktuellen Stand sichern</button><button className="btn primary" disabled={busy} onClick={() => void run(async () => { await onReplace(pending.data); if (pending.userId && pending.revision) await acceptCloudRevision(pending.userId, pending.revision); setPending(null); setMessage('Dein Kochbuch wurde geladen.'); })}>Sicherung übernehmen</button><button className="text-btn" onClick={() => setPending(null)}>Abbrechen</button></div></section>}
    {busy && <p role="status" className="inline"><LoaderCircle className="spin" size={18} />Einen Moment …</p>}{message && <p className="notice" role="status">{message}</p>}{error && <p className="notice error" role="alert">{error}</p>}
    <p className="fineprint inline"><Smartphone size={16} />Du kannst die App über das Browsermenü zum Startbildschirm hinzufügen.</p>
  </div></Modal>;
}
